"""update tables

Revision ID: 56f7a7dc4a27
Revises: 89023d9ea594
Create Date: 2023-10-04 06:06:49.319223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56f7a7dc4a27'
down_revision = '89023d9ea594'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.drop_column('genre')

    # ### end Alembic commands ###
